name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. 依存ライブラリのインストール
      - run: npm ci
      
      # 2. ビルド（distフォルダの作成）
      - run: npm run build
      
      # 3. Firebaseへのデプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STUDY_RECORD_V2 }}'
          channelId: live
          projectId: react-practice-5073c